# Generated by Django 5.2.8 on 2025-11-18 16:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('event_name', models.CharField(max_length=64)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(srid=2385)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('organizer_name', models.CharField(max_length=64)),
                ('organizer_phone', models.CharField(max_length=16)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventareaMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'eventarea_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventEventarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'event_eventarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventStorearea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'event_storearea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=2385)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'facility_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('detail', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=2385)),
            ],
            options={
                'db_table': 'map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Otherarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(srid=2385)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.IntegerField()),
                ('is_public', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otherarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtherareaMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'otherarea_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storearea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(srid=2385)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('store_name', models.CharField(max_length=64)),
                ('owner_name', models.CharField(max_length=64)),
                ('owner_phone', models.CharField(max_length=16)),
                ('logo_url', models.CharField(blank=True, max_length=256, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('api_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'storearea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreareaMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'storearea_map',
                'managed': False,
            },
        ),
    ]
