# Generated by Django 5.2.8 on 2025-12-10 02:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('event_name', models.CharField(max_length=64)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Eventarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(srid=2385)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('organizer_name', models.CharField(max_length=64)),
                ('organizer_phone', models.CharField(max_length=16)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventarea',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=2385)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='Otherarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(srid=2385)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.IntegerField()),
                ('is_public', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otherarea',
            },
        ),
        migrations.CreateModel(
            name='Storearea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(srid=2385)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('store_name', models.CharField(max_length=64)),
                ('owner_name', models.CharField(max_length=64)),
                ('owner_phone', models.CharField(max_length=16)),
                ('logo_url', models.CharField(blank=True, max_length=256, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('api_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'storearea',
            },
        ),
        migrations.CreateModel(
            name='EventEventarea',
            fields=[
                ('pk', models.CompositePrimaryKey('event_id', 'eventarea_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('eventarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventarea')),
            ],
            options={
                'db_table': 'event_eventarea',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('detail', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=2385)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.building')),
            ],
            options={
                'db_table': 'map',
                'unique_together': {('building', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='FacilityMap',
            fields=[
                ('pk', models.CompositePrimaryKey('facility_id', 'map_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facility')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.map')),
            ],
            options={
                'db_table': 'facility_map',
            },
        ),
        migrations.CreateModel(
            name='EventareaMap',
            fields=[
                ('pk', models.CompositePrimaryKey('eventarea_id', 'map_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('eventarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventarea')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.map')),
            ],
            options={
                'db_table': 'eventarea_map',
            },
        ),
        migrations.CreateModel(
            name='OtherareaMap',
            fields=[
                ('pk', models.CompositePrimaryKey('otherarea_id', 'map_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.map')),
                ('otherarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.otherarea')),
            ],
            options={
                'db_table': 'otherarea_map',
            },
        ),
        migrations.CreateModel(
            name='EventStorearea',
            fields=[
                ('pk', models.CompositePrimaryKey('event_id', 'storearea_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('storearea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storearea')),
            ],
            options={
                'db_table': 'event_storearea',
            },
        ),
        migrations.CreateModel(
            name='StoreareaMap',
            fields=[
                ('pk', models.CompositePrimaryKey('storearea_id', 'map_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.map')),
                ('storearea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storearea')),
            ],
            options={
                'db_table': 'storearea_map',
            },
        ),
    ]
